// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQuXt5qjhlK6-lw3vUj5hACjqS7-j_85I',
    appId: '1:933653279572:web:18f42b3809a3e50e014ec1',
    messagingSenderId: '933653279572',
    projectId: 'campuspulse-c487e',
    authDomain: 'campuspulse-c487e.firebaseapp.com',
    storageBucket: 'campuspulse-c487e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUeGLtKKRBB--ciWoBeSQmnKakuV6H17o',
    appId: '1:933653279572:android:64e632152ec88f28014ec1',
    messagingSenderId: '933653279572',
    projectId: 'campuspulse-c487e',
    storageBucket: 'campuspulse-c487e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt8epKf85-ybIHQNnBmrhobIqxx1kimIs',
    appId: '1:933653279572:ios:64de3251d9635fe6014ec1',
    messagingSenderId: '933653279572',
    projectId: 'campuspulse-c487e',
    storageBucket: 'campuspulse-c487e.firebasestorage.app',
    iosBundleId: 'com.example.campuspulseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt8epKf85-ybIHQNnBmrhobIqxx1kimIs',
    appId: '1:933653279572:ios:64de3251d9635fe6014ec1',
    messagingSenderId: '933653279572',
    projectId: 'campuspulse-c487e',
    storageBucket: 'campuspulse-c487e.firebasestorage.app',
    iosBundleId: 'com.example.campuspulseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQuXt5qjhlK6-lw3vUj5hACjqS7-j_85I',
    appId: '1:933653279572:web:a7f4713747a25301014ec1',
    messagingSenderId: '933653279572',
    projectId: 'campuspulse-c487e',
    authDomain: 'campuspulse-c487e.firebaseapp.com',
    storageBucket: 'campuspulse-c487e.firebasestorage.app',
  );
}
